package com.poly.movies.models.dao;

import java.util.List;

import com.poly.movies.models.entities.Favorite;
import com.poly.movies.utils.JPA;
import com.poly.movies.utils.XDate;

import jakarta.persistence.EntityManager;

public class FavoriteDAOImpl implements FavoriteDAO  {

	@Override
		public void create(Favorite e) {
			// TODO Auto-generated method stub
			EntityManager em = JPA.openEntityManager();
			
			try {
				em.getTransaction().begin();
				
				//use this because persist can retrieve identity id
				//in which auto-generated by sql server where a trigger is in front of a insert
				em.createNativeQuery(
			            "INSERT INTO Favorites (userid, videoid, likedDate) VALUES (?, ?, ?)")
			            .setParameter(1, e.getUserId())
			            .setParameter(2, e.getVideoId())
			            .setParameter(3, e.getLikedDate())
			            .executeUpdate();
				
				em.getTransaction().commit();
			} catch (Exception ex) {
				// TODO: handle exception
				ex.printStackTrace();
				em.getTransaction().rollback();
			} finally {
				em.close();
			}
		}

	@Override
	public void update(Favorite e) {
		// TODO Auto-generated method stub
		EntityManager em = JPA.openEntityManager();
		
		try {
			em.getTransaction().begin();
			em.merge(e);
			em.getTransaction().commit();
		} catch (Exception ex) {
			// TODO: handle exception
			ex.printStackTrace();
		} finally {
			em.close();
		}
	}

	@Override
	public void delete(String id) {
		// TODO Auto-generated method stub
		EntityManager em = JPA.openEntityManager();
		
		try {
			em.getTransaction().begin();
			Favorite f = em.find(Favorite.class, id);
			if (f != null) {
				em.remove(f);
			} else {
				System.out.println("Can't find favorite");
			}
			em.getTransaction().commit();
		} catch (Exception ex) {
			// TODO: handle exception
			ex.printStackTrace();
		} finally {
			em.close();
		}
	}

	@Override
	public List<Favorite> findAll() {
		// TODO Auto-generated method stub
		EntityManager em = JPA.openEntityManager();
		
		List<Favorite> beanList = null;
		
		try {
			beanList = em.createQuery("select v from Favorite v", Favorite.class).getResultList();
		} catch (Exception ex) {
			// TODO: handle exception
			ex.printStackTrace();
		} finally {
			em.close();
		}
		
		return beanList;
	}

	@Override
	public Favorite findById(String id) {
		// TODO Auto-generated method stub
		EntityManager em = JPA.openEntityManager();
		
		Favorite bean = null;
		
		try {
			bean = em.find(Favorite.class, id);
		} catch (Exception ex) {
			// TODO: handle exception
			ex.printStackTrace();
		} finally {
			em.close();
		}
		
		return bean;
	}

	@Override
	public Favorite findUserFavoriteVideo(String userId, String videoId) {
		// TODO Auto-generated method stub
		EntityManager em = JPA.openEntityManager();
		Favorite bean = null;
		try {
			bean = em.createQuery("SELECT f FROM Favorite f WHERE f.userId = :userId AND f.videoId = :videoId", Favorite.class)
					.setParameter("userId", userId)
					.setParameter("videoId", videoId)
					.getSingleResult();
		} catch (Exception ex) {
			// TODO: handle exception
			ex.printStackTrace();
		} finally {
			em.close();
		}
		
		return bean;
	}
	
	public static void main(String[] args) {
		FavoriteDAOImpl favoriteDao = new FavoriteDAOImpl();
		Favorite fav = favoriteDao.findUserFavoriteVideo("alice01", "V001");
		System.out.println(fav);
	}

	
}
